/* Official FIFA World Cup 2026 schedule + live results — api.fifa.com */
const OFFICIAL_MATCHES = [
  {no:1, stage:'group', group:'A', round:1, dateMD:'06-11', etHour:15, etMin:0, venue:'MEX', home:'MEX', away:'RSA', homeScore:2, awayScore:0, finished:true},
  {no:2, stage:'group', group:'A', round:1, dateMD:'06-11', etHour:22, etMin:0, venue:'GDL', home:'KOR', away:'CZE', homeScore:2, awayScore:1, finished:true},
  {no:3, stage:'group', group:'B', round:1, dateMD:'06-12', etHour:15, etMin:0, venue:'TOR', home:'CAN', away:'BIH', homeScore:1, awayScore:1, finished:true},
  {no:4, stage:'group', group:'D', round:1, dateMD:'06-12', etHour:21, etMin:0, venue:'LAX', home:'USA', away:'PAR', homeScore:4, awayScore:1, finished:true},
  {no:5, stage:'group', group:'C', round:1, dateMD:'06-13', etHour:21, etMin:0, venue:'BOS', home:'HAI', away:'SCO'},
  {no:6, stage:'group', group:'D', round:1, dateMD:'06-14', etHour:0, etMin:0, venue:'VAN', home:'AUS', away:'TUR'},
  {no:7, stage:'group', group:'C', round:1, dateMD:'06-13', etHour:18, etMin:0, venue:'NYC', home:'BRA', away:'MAR'},
  {no:8, stage:'group', group:'B', round:1, dateMD:'06-13', etHour:15, etMin:0, venue:'SFO', home:'QAT', away:'SUI'},
  {no:9, stage:'group', group:'E', round:1, dateMD:'06-14', etHour:19, etMin:0, venue:'PHL', home:'CIV', away:'ECU'},
  {no:10, stage:'group', group:'E', round:1, dateMD:'06-14', etHour:13, etMin:0, venue:'HOU', home:'GER', away:'CUW'},
  {no:11, stage:'group', group:'F', round:1, dateMD:'06-14', etHour:16, etMin:0, venue:'DAL', home:'NED', away:'JPN'},
  {no:12, stage:'group', group:'F', round:1, dateMD:'06-14', etHour:22, etMin:0, venue:'MTY', home:'SWE', away:'TUN'},
  {no:13, stage:'group', group:'H', round:1, dateMD:'06-15', etHour:18, etMin:0, venue:'MIA', home:'KSA', away:'URU'},
  {no:14, stage:'group', group:'H', round:1, dateMD:'06-15', etHour:12, etMin:0, venue:'ATL', home:'ESP', away:'CPV'},
  {no:15, stage:'group', group:'G', round:1, dateMD:'06-15', etHour:21, etMin:0, venue:'LAX', home:'IRN', away:'NZL'},
  {no:16, stage:'group', group:'G', round:1, dateMD:'06-15', etHour:15, etMin:0, venue:'SEA', home:'BEL', away:'EGY'},
  {no:17, stage:'group', group:'I', round:1, dateMD:'06-16', etHour:15, etMin:0, venue:'NYC', home:'FRA', away:'SEN'},
  {no:18, stage:'group', group:'I', round:1, dateMD:'06-16', etHour:18, etMin:0, venue:'BOS', home:'IRQ', away:'NOR'},
  {no:19, stage:'group', group:'J', round:1, dateMD:'06-16', etHour:21, etMin:0, venue:'KAN', home:'ARG', away:'ALG'},
  {no:20, stage:'group', group:'J', round:1, dateMD:'06-17', etHour:0, etMin:0, venue:'SFO', home:'AUT', away:'JOR'},
  {no:21, stage:'group', group:'L', round:1, dateMD:'06-17', etHour:19, etMin:0, venue:'TOR', home:'GHA', away:'PAN'},
  {no:22, stage:'group', group:'L', round:1, dateMD:'06-17', etHour:16, etMin:0, venue:'DAL', home:'ENG', away:'CRO'},
  {no:23, stage:'group', group:'K', round:1, dateMD:'06-17', etHour:13, etMin:0, venue:'HOU', home:'POR', away:'COD'},
  {no:24, stage:'group', group:'K', round:1, dateMD:'06-17', etHour:22, etMin:0, venue:'MEX', home:'UZB', away:'COL'},
  {no:25, stage:'group', group:'A', round:2, dateMD:'06-18', etHour:12, etMin:0, venue:'ATL', home:'CZE', away:'RSA'},
  {no:26, stage:'group', group:'B', round:2, dateMD:'06-18', etHour:15, etMin:0, venue:'LAX', home:'SUI', away:'BIH'},
  {no:27, stage:'group', group:'B', round:2, dateMD:'06-18', etHour:18, etMin:0, venue:'VAN', home:'CAN', away:'QAT'},
  {no:28, stage:'group', group:'A', round:2, dateMD:'06-18', etHour:21, etMin:0, venue:'GDL', home:'MEX', away:'KOR'},
  {no:29, stage:'group', group:'C', round:2, dateMD:'06-19', etHour:20, etMin:30, venue:'PHL', home:'BRA', away:'HAI'},
  {no:30, stage:'group', group:'C', round:2, dateMD:'06-19', etHour:18, etMin:0, venue:'BOS', home:'SCO', away:'MAR'},
  {no:31, stage:'group', group:'D', round:2, dateMD:'06-19', etHour:23, etMin:0, venue:'SFO', home:'TUR', away:'PAR'},
  {no:32, stage:'group', group:'D', round:2, dateMD:'06-19', etHour:15, etMin:0, venue:'SEA', home:'USA', away:'AUS'},
  {no:33, stage:'group', group:'E', round:2, dateMD:'06-20', etHour:16, etMin:0, venue:'TOR', home:'GER', away:'CIV'},
  {no:34, stage:'group', group:'E', round:2, dateMD:'06-20', etHour:20, etMin:0, venue:'KAN', home:'ECU', away:'CUW'},
  {no:35, stage:'group', group:'F', round:2, dateMD:'06-20', etHour:13, etMin:0, venue:'HOU', home:'NED', away:'SWE'},
  {no:36, stage:'group', group:'F', round:2, dateMD:'06-21', etHour:0, etMin:0, venue:'MTY', home:'TUN', away:'JPN'},
  {no:37, stage:'group', group:'H', round:2, dateMD:'06-21', etHour:18, etMin:0, venue:'MIA', home:'URU', away:'CPV'},
  {no:38, stage:'group', group:'H', round:2, dateMD:'06-21', etHour:12, etMin:0, venue:'ATL', home:'ESP', away:'KSA'},
  {no:39, stage:'group', group:'G', round:2, dateMD:'06-21', etHour:15, etMin:0, venue:'LAX', home:'BEL', away:'IRN'},
  {no:40, stage:'group', group:'G', round:2, dateMD:'06-21', etHour:21, etMin:0, venue:'VAN', home:'NZL', away:'EGY'},
  {no:41, stage:'group', group:'I', round:2, dateMD:'06-22', etHour:20, etMin:0, venue:'NYC', home:'NOR', away:'SEN'},
  {no:42, stage:'group', group:'I', round:2, dateMD:'06-22', etHour:17, etMin:0, venue:'PHL', home:'FRA', away:'IRQ'},
  {no:43, stage:'group', group:'J', round:2, dateMD:'06-22', etHour:13, etMin:0, venue:'DAL', home:'ARG', away:'AUT'},
  {no:44, stage:'group', group:'J', round:2, dateMD:'06-22', etHour:23, etMin:0, venue:'SFO', home:'JOR', away:'ALG'},
  {no:45, stage:'group', group:'L', round:2, dateMD:'06-23', etHour:16, etMin:0, venue:'BOS', home:'ENG', away:'GHA'},
  {no:46, stage:'group', group:'L', round:2, dateMD:'06-23', etHour:19, etMin:0, venue:'TOR', home:'PAN', away:'CRO'},
  {no:47, stage:'group', group:'K', round:2, dateMD:'06-23', etHour:13, etMin:0, venue:'HOU', home:'POR', away:'UZB'},
  {no:48, stage:'group', group:'K', round:2, dateMD:'06-23', etHour:22, etMin:0, venue:'GDL', home:'COL', away:'COD'},
  {no:49, stage:'group', group:'C', round:3, dateMD:'06-24', etHour:18, etMin:0, venue:'MIA', home:'SCO', away:'BRA'},
  {no:50, stage:'group', group:'C', round:3, dateMD:'06-24', etHour:18, etMin:0, venue:'ATL', home:'MAR', away:'HAI'},
  {no:51, stage:'group', group:'B', round:3, dateMD:'06-24', etHour:15, etMin:0, venue:'VAN', home:'SUI', away:'CAN'},
  {no:52, stage:'group', group:'B', round:3, dateMD:'06-24', etHour:15, etMin:0, venue:'SEA', home:'BIH', away:'QAT'},
  {no:53, stage:'group', group:'A', round:3, dateMD:'06-24', etHour:21, etMin:0, venue:'MEX', home:'CZE', away:'MEX'},
  {no:54, stage:'group', group:'A', round:3, dateMD:'06-24', etHour:21, etMin:0, venue:'MTY', home:'RSA', away:'KOR'},
  {no:55, stage:'group', group:'E', round:3, dateMD:'06-25', etHour:16, etMin:0, venue:'PHL', home:'CUW', away:'CIV'},
  {no:56, stage:'group', group:'E', round:3, dateMD:'06-25', etHour:16, etMin:0, venue:'NYC', home:'ECU', away:'GER'},
  {no:57, stage:'group', group:'F', round:3, dateMD:'06-25', etHour:19, etMin:0, venue:'DAL', home:'JPN', away:'SWE'},
  {no:58, stage:'group', group:'F', round:3, dateMD:'06-25', etHour:19, etMin:0, venue:'KAN', home:'TUN', away:'NED'},
  {no:59, stage:'group', group:'D', round:3, dateMD:'06-25', etHour:22, etMin:0, venue:'LAX', home:'TUR', away:'USA'},
  {no:60, stage:'group', group:'D', round:3, dateMD:'06-25', etHour:22, etMin:0, venue:'SFO', home:'PAR', away:'AUS'},
  {no:61, stage:'group', group:'I', round:3, dateMD:'06-26', etHour:15, etMin:0, venue:'BOS', home:'NOR', away:'FRA'},
  {no:62, stage:'group', group:'I', round:3, dateMD:'06-26', etHour:15, etMin:0, venue:'TOR', home:'SEN', away:'IRQ'},
  {no:63, stage:'group', group:'G', round:3, dateMD:'06-26', etHour:23, etMin:0, venue:'SEA', home:'EGY', away:'IRN'},
  {no:64, stage:'group', group:'G', round:3, dateMD:'06-26', etHour:23, etMin:0, venue:'VAN', home:'NZL', away:'BEL'},
  {no:65, stage:'group', group:'H', round:3, dateMD:'06-26', etHour:20, etMin:0, venue:'HOU', home:'CPV', away:'KSA'},
  {no:66, stage:'group', group:'H', round:3, dateMD:'06-26', etHour:20, etMin:0, venue:'GDL', home:'URU', away:'ESP'},
  {no:67, stage:'group', group:'L', round:3, dateMD:'06-27', etHour:17, etMin:0, venue:'NYC', home:'PAN', away:'ENG'},
  {no:68, stage:'group', group:'L', round:3, dateMD:'06-27', etHour:17, etMin:0, venue:'PHL', home:'CRO', away:'GHA'},
  {no:69, stage:'group', group:'J', round:3, dateMD:'06-27', etHour:22, etMin:0, venue:'KAN', home:'ALG', away:'AUT'},
  {no:70, stage:'group', group:'J', round:3, dateMD:'06-27', etHour:22, etMin:0, venue:'DAL', home:'JOR', away:'ARG'},
  {no:71, stage:'group', group:'K', round:3, dateMD:'06-27', etHour:19, etMin:30, venue:'MIA', home:'COL', away:'POR'},
  {no:72, stage:'group', group:'K', round:3, dateMD:'06-27', etHour:19, etMin:30, venue:'ATL', home:'COD', away:'UZB'},
  {no:73, stage:'r32', round:'Round of 32', dateMD:'06-28', etHour:15, etMin:0, venue:'LAX', home:'RSA', away:'CAN', homeScore:0, awayScore:1, finished:true},
  {no:74, stage:'r32', round:'Round of 32', dateMD:'06-29', etHour:16, etMin:30, venue:'BOS', home:'GER', away:'PAR'},
  {no:75, stage:'r32', round:'Round of 32', dateMD:'06-29', etHour:21, etMin:0, venue:'MTY', home:'NED', away:'MAR'},
  {no:76, stage:'r32', round:'Round of 32', dateMD:'06-29', etHour:13, etMin:0, venue:'HOU', home:'BRA', away:'JPN'},
  {no:77, stage:'r32', round:'Round of 32', dateMD:'06-30', etHour:17, etMin:0, venue:'NYC', home:'FRA', away:'SWE'},
  {no:78, stage:'r32', round:'Round of 32', dateMD:'06-30', etHour:13, etMin:0, venue:'DAL', home:'CIV', away:'NOR'},
  {no:79, stage:'r32', round:'Round of 32', dateMD:'06-30', etHour:21, etMin:0, venue:'MEX', home:'MEX', away:'ECU'},
  {no:80, stage:'r32', round:'Round of 32', dateMD:'07-01', etHour:12, etMin:0, venue:'ATL', home:'ENG', away:'COD'},
  {no:81, stage:'r32', round:'Round of 32', dateMD:'07-01', etHour:20, etMin:0, venue:'SFO', home:'USA', away:'BIH'},
  {no:82, stage:'r32', round:'Round of 32', dateMD:'07-01', etHour:16, etMin:0, venue:'SEA', home:'BEL', away:'SEN'},
  {no:83, stage:'r32', round:'Round of 32', dateMD:'07-02', etHour:19, etMin:0, venue:'TOR', home:'POR', away:'CRO'},
  {no:84, stage:'r32', round:'Round of 32', dateMD:'07-02', etHour:15, etMin:0, venue:'LAX', home:'ESP', away:'AUT'},
  {no:85, stage:'r32', round:'Round of 32', dateMD:'07-02', etHour:23, etMin:0, venue:'VAN', home:'SUI', away:'ALG'},
  {no:86, stage:'r32', round:'Round of 32', dateMD:'07-03', etHour:18, etMin:0, venue:'MIA', home:'ARG', away:'CPV'},
  {no:87, stage:'r32', round:'Round of 32', dateMD:'07-03', etHour:21, etMin:30, venue:'KAN', home:'COL', away:'GHA'},
  {no:88, stage:'r32', round:'Round of 32', dateMD:'07-03', etHour:14, etMin:0, venue:'DAL', home:'AUS', away:'EGY'},
  {no:89, stage:'r16', round:'Round of 16', dateMD:'07-04', etHour:17, etMin:0, venue:'PHL', homeLabel:'W74', awayLabel:'W77'},
  {no:90, stage:'r16', round:'Round of 16', dateMD:'07-04', etHour:13, etMin:0, venue:'HOU', homeLabel:'W73', awayLabel:'W75'},
  {no:91, stage:'r16', round:'Round of 16', dateMD:'07-05', etHour:16, etMin:0, venue:'NYC', homeLabel:'W76', awayLabel:'W78'},
  {no:92, stage:'r16', round:'Round of 16', dateMD:'07-05', etHour:20, etMin:0, venue:'MEX', homeLabel:'W79', awayLabel:'W80'},
  {no:93, stage:'r16', round:'Round of 16', dateMD:'07-06', etHour:15, etMin:0, venue:'DAL', homeLabel:'W83', awayLabel:'W84'},
  {no:94, stage:'r16', round:'Round of 16', dateMD:'07-06', etHour:20, etMin:0, venue:'SEA', homeLabel:'W81', awayLabel:'W82'},
  {no:95, stage:'r16', round:'Round of 16', dateMD:'07-07', etHour:12, etMin:0, venue:'ATL', homeLabel:'W86', awayLabel:'W88'},
  {no:96, stage:'r16', round:'Round of 16', dateMD:'07-07', etHour:16, etMin:0, venue:'VAN', homeLabel:'W85', awayLabel:'W87'},
  {no:97, stage:'qf', round:'Quarter-final', dateMD:'07-09', etHour:16, etMin:0, venue:'BOS', homeLabel:'W89', awayLabel:'W90'},
  {no:98, stage:'qf', round:'Quarter-final', dateMD:'07-10', etHour:15, etMin:0, venue:'LAX', homeLabel:'W93', awayLabel:'W94'},
  {no:99, stage:'qf', round:'Quarter-final', dateMD:'07-11', etHour:17, etMin:0, venue:'MIA', homeLabel:'W91', awayLabel:'W92'},
  {no:100, stage:'qf', round:'Quarter-final', dateMD:'07-11', etHour:21, etMin:0, venue:'KAN', homeLabel:'W95', awayLabel:'W96'},
  {no:101, stage:'sf', round:'Semi-final', dateMD:'07-14', etHour:15, etMin:0, venue:'DAL', homeLabel:'W97', awayLabel:'W98'},
  {no:102, stage:'sf', round:'Semi-final', dateMD:'07-15', etHour:15, etMin:0, venue:'ATL', homeLabel:'W99', awayLabel:'W100'},
  {no:103, stage:'final', round:'Third-place Play-off', dateMD:'07-18', etHour:17, etMin:0, venue:'MIA', homeLabel:'RU101', awayLabel:'RU102'},
  {no:104, stage:'final', round:'Final', dateMD:'07-19', etHour:15, etMin:0, venue:'NYC', homeLabel:'W101', awayLabel:'W102'},
];